build and add tag

diff --git a/.github/workflows/azure-container-webapp.yml b/.github/workflows/azure-container-webapp.yml
--- a/.github/workflows/azure-container-webapp.yml
+++ b/.github/workflows/azure-container-webapp.yml
@@ -33,6 +33,40 @@ jobs:
               docker push creuwbfcommonsd.azurecr.io/sharedservices/librechat:${{ github.sha }}
 
 
+          - name: Generate Token
+            id: create_token
+            uses: tibdex/github-app-token@v2
+            with:
+              app_id: 1295399
+              private_key: ${{ secrets.PEM_TO_BOOKINGS_INFRA }}
+              installation_retrieval_mode: repository
+              installation_retrieval_payload: businessfinland/libre-chat-infra
+              revoke: true
+
+          - name: Update CONTAINER_IMAGE_NAME_DEV variable
+            env:
+              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
+              TARGET_REPO_NAME: 'businessfinland/libre-chat-infra'
+            run: |
+                curl -X PATCH \
+                -H "Authorization: Bearer $INSTALLATION_TOKEN" \
+                -H "Accept: application/vnd.github+json" \
+                "https://api.github.com/repos/$TARGET_REPO_NAME/actions/variables/CONTAINER_IMAGE_NAME_DEV" \
+                -d "{\"value\":\"${{ github.sha }}\"}" \
+                || { echo "Failed to update variable"; exit 1; }
+
+          - name: Trigger Deployment Workflow
+            env:
+              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
+              TARGET_REPO_NAME: 'businessfinland/libre-chat-infra'
+            run: |
+              # Trigger the deployment workflow
+                curl -X POST \
+                  -H "Authorization: Bearer $INSTALLATION_TOKEN" \
+                  -H "Accept: application/vnd.github+json" \
+                  "https://api.github.com/repos/$TARGET_REPO_NAME/actions/workflows/dev-deploy-infra.yml/dispatches" \
+                  -d '{"ref":"main"}'
+
     build-and-push-test:
         needs : build-and-push-dev
         runs-on: ubuntu-latest
